name: PR

on:
  pull_request:
    branches:
      - "**"

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-
      - run: yarn install --frozen-lockfile
      - run: yarn tsc
      - run: yarn lint
      - run: yarn build
