name: PR

on:
  pull_request:
    branches:
      - "**"

env:
  CARGO_INCREMENTAL: 0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-v1-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-v1-
      - uses: umidbekk/actions/npm/install@v1
      - run: yarn build
      - run: yarn tsc
      - run: yarn lint
      - run: yarn test
